In [ ]:
# Git commands
"""
git config user.name -- to set username locally (--global)
git config user.email -- to set email locally 
git config --unset user.name -- to remove username locally 
git config --unset user.email -- to remove email locally

Alt + F7 -- to delete your command line history
"""

# Basic Python Learning

## Tuple
This is immutable, you can't change it's structure

In [ ]:
tup = (1,2,3,4,5)
# or 
tup = 1,2,3,4,5
# or
tup = tuple([1,2,3,4,5])

In [ ]:
seq = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
for a, b, c in seq:    
    print(f'a={a}, b={b}, c={c}')

In [ ]:
tup = (1, 2, 2, 2, 3, 4, 2)
q, w, *_ = tup
"""
q --> 1
w --> 2
_ --> [2, 2, 3, 4, 2]
"""

In [45]:
tup = (1, 2) + (3, 4) + (5,)
tup

(1, 2, 3, 4, 5)

## List
This one is mutable. you can change it's structure

In [41]:
li = [1, 2, 3, 4, 5]
# or
li = list((1, 2, 3, 4, 5))

In [ ]:
# list.append() --> add an element to the end of the list
# list.insert(index, element) --> add an element at a specific position in the list
# list.pop(index) --> remove and return the element at the specified index (default is the last element)
# list.remove(element) --> remove the first occurrence of the specified element from the list
# list.clear() --> remove all elements from the list
# element in list --> check if an element is in the list (returns True or False)

In [ ]:
[1, 2] + [3, 4] + [5]
# list.extend(iterable) --> add all elements of an iterable to the end of the list
"""
list.extend(iterable) is faster than list concatenation (using +) because it modifies the list in place, 
while list concatenation creates a new list. When you use list concatenation, Python creates a new list and copies all the elements from the original lists into it, 
which can be time-consuming for large lists. On the other hand, list.extend() simply adds the elements of the iterable to the existing list without creating a new one, making it more efficient.
"""

[1, 2, 3, 4, 5]

### Sorting

In [49]:
a = [7, 2, 5, 1, 3]
a.sort()
a

[1, 2, 3, 5, 7]

In [52]:
b = ["aaaa", "aa", "a", "aaa"]
b.sort(key=len)
b

['a', 'aa', 'aaa', 'aaaa']

### Slicing

In [53]:
# list[start:stop:step] --> slicing a list
seq = [7, 2, 3, 7, 5, 6, 0, 1]
seq[1:5]  # elements from index 1 to 4

[2, 3, 7, 5]

In [58]:
seq[::2]  # every second element

[7, 3, 5, 0]

In [59]:
seq[::-1]  # reverse the list

[1, 0, 6, 5, 7, 3, 2, 7]

In [60]:
seq[3:5] = [10, 11]  # replace elements at index 3 and 4 with 10 and 11
seq

[7, 2, 3, 10, 11, 6, 0, 1]

![SLICING](slicing.png)

## Dictionary
Stores a collection of key-value pairs, where key and value are Python objects.

In [2]:
dic = {'a': 1, 'b': 2, 'c': 3}
# or
dic = dict(a=1, b=2, c=3)

In [3]:
dic['a']  # access value by key

1

In [4]:
'b' in dic  # check if a key is in the dictionary (returns True or False)

True

In [5]:
dic['d'] = 4  # add a new key-value pair to the dictionary
dic

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [6]:
del dic['d'] # remove a key-value pair from the dictionary
dic

{'a': 1, 'b': 2, 'c': 3}

In [7]:
dic.pop('c')  # remove and return the value associated with the key 'c'

3

In [9]:
dic.keys()  # get a view of the dictionary's keys
dic.values()  # get a view of the dictionary's values
dic.items()  # get a view of the dictionary's key-value pairs

dict_items([('a', 1), ('b', 2)])

In [11]:
dic.update({'d': 4, 'e': 5})  # update the dictionary with key-value pairs from another dictionary or iterable of key-value pairs

In [12]:
dic

{'a': 1, 'b': 2, 'd': 4, 'e': 5}

In [13]:
dic.update({'d': 6, 'c': 3}) # update the value of an existing key 'd' to 6 and add a new key 'c' with value 3
dic

{'a': 1, 'b': 2, 'd': 6, 'e': 5, 'c': 3}

In [15]:
for key, value in dic.items():
    print(f'Key: {key}, Value: {value}')

Key: a, Value: 1
Key: b, Value: 2
Key: d, Value: 6
Key: e, Value: 5
Key: c, Value: 3

In [17]:
dic.get('f', 'Not found')  # get the value associated with key 'f', or return 'Not found' if 'f' is not in the dictionary

'Not found'

In [18]:
words = ["apple", "bat", "bar", "atom", "book"]
by_letter = {}
for word in words:
    letter = word[0]  # get the first letter of the word
    if letter not in by_letter:
        by_letter[letter] = [word]  # create a new list for this letter
    else:
        by_letter[letter].append(word)  # add the word to the existing list for this letter
by_letter

{'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']}

In [20]:
by_letter.clear()
for word in words:
    letter = word[0]
    by_letter.setdefault(letter, []).append(word)  # setdefault() returns the value of the key if it is in the dictionary; if not, it inserts the key with a default value (in this case, an empty list) and returns that value, then appends the word to the list
by_letter

{'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']}

In [21]:
from collections import defaultdict
by_letter = defaultdict(list)  # create a defaultdict where the default value for any key is an empty list
for word in words:
    letter = word[0]
    by_letter[letter].append(word)  # append the word to the list for this letter (if the letter is not already a key in the dictionary, it will be created with an empty list as the default value)
by_letter

defaultdict(list, {'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']})

## Set 
An unordered collection of unique elements

In [22]:
s = set([2, 2, 2, 1, 3, 3])
# or 
s = {2, 2, 2, 1, 3, 3}

### Mathematical operations (union, intersection, symmertic | difference)

In [24]:
a = {1, 2, 3, 4, 5}
b = {3, 4, 5, 6, 7, 8}
a.union(b)

{1, 2, 3, 4, 5, 6, 7, 8}

In [25]:
a.intersection(b)
# or 
a & b

{3, 4, 5}

![SET_OPER](set_operations.png)

## Built-In Sequence Functions

In [31]:
# enumerate() --> adds a counter to an iterable and returns it as an enumerate object, which can be converted to a list of tuples (index, element)
fruits = ["apple", "banana", "cherry"]
print(list(enumerate(fruits)))  # returns a list of tuples (index, element)
for index, fruit in enumerate(fruits):
    print(f"Index {index}: {fruit}")

[(0, 'apple'), (1, 'banana'), (2, 'cherry')]
Index 0: apple
Index 1: banana
Index 2: cherry

In [32]:
# sorted --> returns a new sorted list from the items in an iterable
numbers = [5, 2, 9, 1, 5, 6]
sorted(numbers)

[1, 2, 5, 5, 6, 9]

In [35]:
# zip() --> pairs up the elements of lists, tuples or other sequences
seq1 = ['name', 'surname', 'age']
seq2 = ('Dias', 'Onaibaev', 21)

zipped = list(zip(seq1, seq2))  # returns a list of tuples (index, element)
zipped

[('name', 'Dias'), ('surname', 'Onaibaev'), ('age', 21)]

## Comprehensions

In [39]:
# [expr for value in collection if condition] --> list comprehension, a concise way to create lists
strings = ["a", "as", "bat", "car", "dove", "python"]
tuple([x.upper() for x in strings if len(x) > 2])

('BAT', 'CAR', 'DOVE', 'PYTHON')

In [ ]:
# dict_comp = {key-expr: value-expr for value in collection if condition}
# set_comp = {expr for value in collection if condition}

In [ ]:
# map(func, *iterables) --> applies a function to every item of an iterable (or iterables) and returns a map object (which is an iterator)

## Functions

In [6]:
# functions as objects --> in Python, functions are first-class objects, which means they can be passed around and used as arguments just like any other object (string, int, float, list, etc.)
import re
states = ["   Alabama ", "Georgia!", "Georgia", "georgia", "FlOrIda", "south   carolina##", "West virginia?"]

def remove_punctuation(value):
    return re.sub("[!#?]", "", value)

clean_ops = [str.strip, remove_punctuation, str.title]

def clean_strings(strings, ops):
    result = []
    for value in strings:
        for func in ops:
            value = func(value)
        result.append(value)
    return result

clean_strings(states, clean_ops)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']

### Anonymous (Lambda) Functions

In [7]:
def short_function(x):
    return x * 2

# is equivalent to

equal_short_function = lambda x: x * 2

equal_short_function(5)  # returns 10

10

In [ ]:
strings = ["foo", "card", "bar", "aaaa", "abab"]

strings.sort(key=lambda x: len(set(x)))
# set is needed here because we want to sort the strings based on the number of unique characters they contain.
strings

['foo', 'bar', 'card', 'aaaa', 'abab']

### Generators

In [ ]:
"""
a generator is a special kind of function that lets you produce a sequence of values over time, 
instead of creating them all at once and saving them in memory.
"""

def ret():
    for i in range(5):
        yield i  # yield is used to create a generator, which is an iterator that generates values on the fly and can be iterated over using a for loop or next() function    

gen = ret()

In [15]:
# (value for value in collection) --> generator expression, a concise way to create generators
squares_gen = (x**2 for x in range(1000000))

print(next(squares_gen))  
print(next(squares_gen))  
print(next(squares_gen))  
print(next(squares_gen))  
print(next(squares_gen))

0
1
4
9
16

In [ ]:
"""Depending on the number of elements produced by the comprehension expression,
the generator version can sometimes be meaningfully faster than the list version,
but the main advantage is that it does not require the memory to store the entire list in memory"""
sum(x**2 for x in range(1000000))  
# or
sum([x**2 for x in range(1000000)]) 
# it will create a list in memory, which can be inefficient for large ranges, 
# while the generator expression will generate each value on the fly and not require additional memory to store the entire list.

#### itertools

In [8]:
import itertools
"""
itertools module provides a collection of tools for handling iterators, 
which can be used to create efficient loops and iterators for various tasks, 
such as creating combinations, permutations, and infinite iterators.
"""

def first_letter(word):
    return word[0]

names = ["Alan", "Adam", "Wes", "Will", "Albert", "Steven"]

for letter, names in itertools.groupby(sorted(names), first_letter):
    print(f"{letter}: {list(names)}")

A: ['Adam', 'Alan', 'Albert']
S: ['Steven']
W: ['Wes', 'Will']

## Errors and Exception Handling

In [ ]:
try:
    # 1. The "Dangerous" Zone
    # Put code here that might fail (e.g., opening a file, dividing numbers)
    pass

except ValueError:
    # 2. The Contingency Plan
    # Runs ONLY if a 'ValueError' happens inside the try block
    pass

except (TypeError, ZeroDivisionError):
    # You can catch multiple exceptions in a single except block by using a tuple of exception types
    pass

# BETTER: Catching the error object to see Python's built-in message
except ValueError as e:
    print(f"Failed because of: {e}")

else:
    # 3. The "All Clear" Zone
    # Runs ONLY if the try block completed perfectly with ZERO errors
    pass

finally:
    # 4. The "No Matter What" Zone
    # Runs always, whether an error happened or not (used for cleanup)
    pass

In [ ]:
def set_age(age):
    if age < 0:
        # Stop the program immediately because a negative age makes no sense
        raise ValueError("Age cannot be negative!")
    return age

In [ ]:
class APIError(Exception):
    """Custom exception for our web application"""
    pass

def get_user_profile(user_id):
    try:
        # Imagine the database server is down
        return connect_to_db().query(f"SELECT * FROM users WHERE id={user_id}")
    except ConnectionRefusedError as db_error:
        # Cleanly convert a infrastructure error into an application error
        raise APIError("Could not fetch user profile details") from db_error

```pytb
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 10, in get_user_profile
    raise APIError("Could not fetch user profile details") from db_error
__main__.APIError: Could not fetch user profile details
```

## Files and the Operating System

In [1]:
PATH = "file.txt"
f = open(PATH, encoding='utf-8')

![MODE](file_mode.png)

In [ ]:
# We can treat the file object as a sequence of lines
for line in f:
    print(line)

Sueña el rico en su riqueza,

que más cuidados le ofrece;



sueña el pobre que padece

su miseria y su pobreza;



sueña el que a medrar empieza,

sueña el que afana y pretende,

sueña el que agravia y ofende,



y en el mundo, en conclusión,

todos sueñan lo que son,

aunque ninguno lo entiende.

In [3]:
lines = [x.rstrip() for x in open(PATH, encoding='utf-8')]
lines

['Sueña el rico en su riqueza,',
 'que más cuidados le ofrece;',
 '',
 'sueña el pobre que padece',
 'su miseria y su pobreza;',
 '',
 'sueña el que a medrar empieza,',
 'sueña el que afana y pretende,',
 'sueña el que agravia y ofende,',
 '',
 'y en el mundo, en conclusión,',
 'todos sueñan lo que son,',
 'aunque ninguno lo entiende.']

In [4]:
# Closing the file releases its resources back to the operating system, which is important to 
# prevent resource leaks and ensure that other processes can access the file if needed. 
# It also ensures that any changes made to the file are properly saved and that the file is not left in an inconsistent state.
f.close()

In [6]:
with open(PATH, encoding='utf-8') as f:
    lines = [x.rstrip() for x in f]
# The with statement automatically takes care of closing the file after the block of code is executed, 
# even if an error occurs within the block.
lines

['Sueña el rico en su riqueza,',
 'que más cuidados le ofrece;',
 '',
 'sueña el pobre que padece',
 'su miseria y su pobreza;',
 '',
 'sueña el que a medrar empieza,',
 'sueña el que afana y pretende,',
 'sueña el que agravia y ofende,',
 '',
 'y en el mundo, en conclusión,',
 'todos sueñan lo que son,',
 'aunque ninguno lo entiende.']

In [42]:
f1 = open(PATH, encoding='utf-8')
f1.read(10)  # read the first 10 characters of the file
# once you have read the first 10 characters, the file pointer is now at the 11th character, 
# so if you call f1.read() again, it will continue reading from where it left off, 
# rather than starting from the beginning of the file.

'Sueña el r'

In [13]:
f1.tell()  # returns the current position of the file pointer (in bytes)

11

In [12]:
f2 = open(PATH, mode='rb') # open the file in binary mode (read bytes instead of text)
f2.read(10)  # read the first 10 bytes of the file

b'Sue\xc3\xb1a el '

In [14]:
f2.tell()

10

In [15]:
# file.seek(offset, whence)   
"""
offset --> the number of bytes to move the file pointer
whence --> the reference point for the offset (0 for the beginning of the file, 1 for the current position, 2 for the end of the file)
whence 1, 2 works only on binary files, for text files, only whence 0 is allowed
"""

f1.seek(0)
f1.tell()  # after seeking to the beginning of the file, the file pointer is now at position 0

0

In [34]:
# remove blank lines and write the result to a new file
with open('tmp.txt', mode="w") as handle:
    handle.writelines(x for x in open(PATH) if len(x) > 1)

In [41]:
with open("tmp.txt", encoding='utf-8') as f:
    lines = f.readlines()  # readlines() reads the entire file and returns a list of lines
lines

['Sueña el rico en su riqueza,\n',
 'que más cuidados le ofrece;\n',
 'sueña el pobre que padece\n',
 'su miseria y su pobreza;\n',
 'sueña el que a medrar empieza,\n',
 'sueña el que afana y pretende,\n',
 'sueña el que agravia y ofende,\n',
 'y en el mundo, en conclusión,\n',
 'todos sueñan lo que son,\n',
 'aunque ninguno lo entiende.\n']

In [46]:
with open(PATH, mode="rb") as f:
    data = f.read(10)
data

b'Sue\xc3\xb1a el '

In [47]:
data.decode('utf-8')  # decode the bytes to a string using UTF-8 encoding

'Sueña el '

In [ ]:
data[:4].decode('utf-8')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 3: unexpected end of data

In [ ]:
"""
Depending on the text encoding, you may be able to decode the bytes to a str object
yourself, but only if each of the encoded Unicode characters is fully formed
"""
data[:5].decode('utf-8')

'Sueñ'

# Pandas

In [57]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.

## Series

In [58]:
obj = pd.Series([4, 7, -5, 3])

In [61]:
obj.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [62]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [63]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [64]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='str')

In [65]:
obj2['e'] = 1

In [67]:
obj2.index

Index(['d', 'b', 'a', 'c', 'e'], dtype='str')

In [74]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
obj3 = pd.Series(sdata)
# Series is like a dictionary
# obj3 = obj3.index + obj3.values | obj3.array
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [78]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [ ]:
# pd.isna() --> returns a boolean Series indicating whether each value is NA (missing) or not
# pd.notna() --> returns a boolean Series indicating whether each value is NOT NA (not missing) or not
pd.isna(obj4)
obj4.isna()

np.int64(4)

In [ ]:
obj3["Ohio"] = 30000
obj3

Ohio      30000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [87]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [ ]:
obj3 + obj4 # adds values for matching indices and produces NA for non-matching indices

California         NaN
Ohio           65000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [91]:
obj4.name = "population"
obj4.index.name = "state"
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [92]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [93]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [94]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [97]:
data = {
    "state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
    "year": [2000, 2001, 2002, 2001, 2002, 2003],
    "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}
frame = pd.DataFrame(data)
# pd.DataFrame(data, columns=["year", "state", "pop"]) --> specify the order of columns in the DataFrame
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [ ]:
frame.loc[1]

state    Ohio
year     2001
pop       1.7
Name: 1, dtype: object

In [101]:
frame = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])
frame

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [104]:
frame["debt"] = np.arange(6.)
frame

   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [106]:
val = pd.Series([-1.2, -1.5, -1.7], index=['a', 'b', 'c'])
frame["debt"] = val
frame

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [107]:
populations = {
    "Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
    "Nevada": {2001: 2.4, 2002: 2.9}
}
frame3 = pd.DataFrame(populations)
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [111]:
frame3.index.name = "year"
frame3.columns.name = "state"
frame3

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [ ]:
# loc[:] -> works only on labels (index and column names)
# iloc[:] -> works only on integer positions (like a regular NumPy array) whether the index is integer or not

# In DataFrame
# loc[index, columns]
# iloc[row_positions, column_positions]

In [ ]:
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])
obj2.loc["a":"b"]  # loc includes the stop label
obj2.iloc[0:2] # iloc does not include the stop index

a    1
b    2
c    3
dtype: int64

In [116]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),                 
index=["Ohio", "Colorado", "Utah", "New York"],
columns=["one", "two", "three", "four"])

data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [118]:
data[data < 5] = 0
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

![LOC](loc.png)

In [123]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),  
columns=list("bde"),
index=["Utah", "Ohio", "Texas", "Oregon"])

In [124]:
frame

               b         d         e
Utah    0.064521  0.950331  0.714693
Ohio    0.250354  0.081893  1.137788
Texas   0.322547  1.384444 -0.522343
Oregon  0.009803 -0.527579  1.250061

In [125]:
np.abs(frame)

               b         d         e
Utah    0.064521  0.950331  0.714693
Ohio    0.250354  0.081893  1.137788
Texas   0.322547  1.384444  0.522343
Oregon  0.009803  0.527579  1.250061